version: '3.1'
services:
  postgreSQL:
    image: "postgres:14"
    container_name: dbpostgresql
    networks:
      - order-pgsql
    ports:
      - "5432:5432"
    volumes:
      - /home/xbakhromjon/docker/postgres/docker-pg-vol/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    container_name: outgoing
    image: outgoing
    networks:
      - order-pgsql
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/outgoing
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_SHOW_SQL=true

networks:
  order-pgsql: